const mockTask = "Prepare hot chocolate."
const mockEnvironment = "kitchen, milk, cocoa, sugar, pan, spoon, cabinet, mug, chair, sink. The mug is in the closet. The sink is located next to the stove. Milk, cocoa, sugar and a spoon are on the table. The pan is on the stove."
const mockOptimalPlan = "Open the door. Walk to the kitchen. Close the door. Find a table. Come to the table. Find milk. Grab milk. Find a saucepan. Grab a saucepan. Pour the milk into the pan. Remove the milk. Place the pan on the table. Find cocoa. Grab some cocoa. Add cocoa to the pan. Remove the cocoa. Find sugar. Grab sugar. Add sugar to the pan. Remove the sugar. Find a spoon. Grab a spoon. Stir everything in the the pan with a spoon. Remove the spoon. Find a saucepan. Grab a saucepan. Find the stove. Place the pan on the stove. Switch on the stove. Select temperature. Select the heating time. Wait for it to boil. Find a spoon. Grab a spoon. Stir the milk with a spoon. Switch off the stove. Stir hot chocolate into saucepan. Find a sink. Walk to the sink. Place the spoon in the the sink. Find a closet. Open the door. Find a mug. Grab a mug. Close the door. Find a table. Come to the table. Put down the mug. Find the stove. Walk to the stove. Find a saucepan. Grab the pot. Find a table. Come to the table. Find a mug. Pour hot chocolate into a mug. Find the stove. Walk to the stove. Place the saucepan. Find a table. Come to the table. Find a chair. Pull your chair back. Sit on a chair. Drink hot chocolate."
const mockPredictedPlan = "Open the door. Walk to the kitchen. Close the door. Find a table. Come to the table. Find milk. Grab milk. Find a saucepan. Grab a saucepan. Pour the milk into the pan. Remove the milk. Place the pan on the table. Find cocoa. Grab some cocoa. Add cocoa to the pan. Remove the cocoa. Find sugar. Grab sugar. Add sugar to the pan. Remove the sugar. Find a spoon. Grab a spoon. Stir everything in the the pan with a spoon. Remove the spoon. Find a saucepan. Grab a saucepan. Find the stove. Place the pan on the stove. Switch on the stove. Select temperature. Select the heating time. Wait for it to boil. Find a spoon. Grab a spoon. Stir the milk with a spoon. Switch off the stove. Stir hot chocolate into saucepan. Find a sink. Walk to the sink. Place the spoon in the the sink. Find a closet. Open the door. Find a mug. Grab a mug. Close the door. Find a table. Come to the table. Put down the mug. Find the stove. Walk to the stove. Find a saucepan. Grab the pot. Find a table. Come to the table. Find a mug. Pour hot chocolate into a mug. Find the stove. Walk to the stove. Place the saucepan. Find a table. Come to the table. Find a chair. Pull your chair back. Sit on a chair. Drink hot chocolate."
export {
    mockTask,
    mockEnvironment,
    mockOptimalPlan,
    mockPredictedPlan
}